# This file is placed in the public domain.

# Note: this is both a Makefile and a shell script. It is included from both a
# Makefile and from a shell script to define version numbers in a central
# place. Therefore, this file should be kept compatible with both syntaxes.

# These are the values for macOS 11.5:
# https://opensource.apple.com/release/macos-115.html
AvailabilityVersions_version=80.3
Libc_version=1439.141.1
libmalloc_version=317.140.5
libpthread_version=454.120.2
xnu_version=7195.141.2

# These are not part of the list above and don't seem to have any updates
# recently.
CarbonHeaders_version=18.1
Libm_version=2026
