name: Test sysroots
on: [push]
jobs:
  Test-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
      - name: Run tests
        run: make test CLANG=clang-20
  Test-MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Clang
        run: brew install llvm lld
      - name: Run tests
        run: make test CLANG=$(brew --prefix llvm)/bin/clang
  Test-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run tests
        run: make test CLANG=clang
